//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Crayon.Wlw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DC.Crayon.Wlw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred while downloading the requested resource - &apos;{0}&apos;.
        /// </summary>
        internal static string Error_DownloadError_Error {
            get {
                return ResourceManager.GetString("Error_DownloadError_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string Error_FieldRequired {
            get {
                return ResourceManager.GetString("Error_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not valid. Expected format is &quot;1,3-5,8...&quot;.
        /// </summary>
        internal static string Error_InvalidLineNumberRange {
            get {
                return ResourceManager.GetString("Error_InvalidLineNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the latest release details from the server.
        /// </summary>
        internal static string Error_UpdateCheckFailure {
            get {
                return ResourceManager.GetString("Error_UpdateCheckFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Group_Code {
            get {
                return ResourceManager.GetString("Group_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Group_Content {
            get {
                return ResourceManager.GetString("Group_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom options.
        /// </summary>
        internal static string Group_CustomOptions {
            get {
                return ResourceManager.GetString("Group_CustomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Group_Font {
            get {
                return ResourceManager.GetString("Group_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Group_Lines {
            get {
                return ResourceManager.GetString("Group_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        internal static string Group_Metrics {
            get {
                return ResourceManager.GetString("Group_Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Group_Theme {
            get {
                return ResourceManager.GetString("Group_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string Group_Toolbar {
            get {
                return ResourceManager.GetString("Group_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow mixed language highlighting with delimiters and tags.
        /// </summary>
        internal static string Help_Code_AllowMixedLanguageHighlightingWithDelimitersAndTags {
            get {
                return ResourceManager.GetString("Help_Code_AllowMixedLanguageHighlightingWithDelimitersAndTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always display scrollbars.
        /// </summary>
        internal static string Help_Code_AlwaysDisplayScrollbars {
            get {
                return ResourceManager.GetString("Help_Code_AlwaysDisplayScrollbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank lines after code.
        /// </summary>
        internal static string Help_Code_BlankLinesAfterCode {
            get {
                return ResourceManager.GetString("Help_Code_BlankLinesAfterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank lines before code.
        /// </summary>
        internal static string Help_Code_BlankLinesBeforeCode {
            get {
                return ResourceManager.GetString("Help_Code_BlankLinesBeforeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode html entities in attributes.
        /// </summary>
        internal static string Help_Code_DecodeHtmlEntitiesInAttributes {
            get {
                return ResourceManager.GetString("Help_Code_DecodeHtmlEntitiesInAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable code expanding toggling.
        /// </summary>
        internal static string Help_Code_EnableCodeExpandingToggling {
            get {
                return ResourceManager.GetString("Help_Code_EnableCodeExpandingToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable copy paste.
        /// </summary>
        internal static string Help_Code_EnableCopyPaste {
            get {
                return ResourceManager.GetString("Help_Code_EnableCopyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable open in new window.
        /// </summary>
        internal static string Help_Code_EnableOpenInNewWindow {
            get {
                return ResourceManager.GetString("Help_Code_EnableOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable plain code toggling.
        /// </summary>
        internal static string Help_Code_EnablePlainCodeToggling {
            get {
                return ResourceManager.GetString("Help_Code_EnablePlainCodeToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable plain code view.
        /// </summary>
        internal static string Help_Code_EnablePlainCodeView {
            get {
                return ResourceManager.GetString("Help_Code_EnablePlainCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand code beyond page border on mouse hover.
        /// </summary>
        internal static string Help_Code_ExpandCodeBeyondPageBorderOnMouseHover {
            get {
                return ResourceManager.GetString("Help_Code_ExpandCodeBeyondPageBorderOnMouseHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize code.
        /// </summary>
        internal static string Help_Code_MinimizeCode {
            get {
                return ResourceManager.GetString("Help_Code_MinimizeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain code view display trigger.
        /// </summary>
        internal static string Help_Code_PlainCodeViewDisplayTrigger {
            get {
                return ResourceManager.GetString("Help_Code_PlainCodeViewDisplayTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove code tags surrounding shortcode content.
        /// </summary>
        internal static string Help_Code_RemoveCodeTagsSurroundingShortcodeContent {
            get {
                return ResourceManager.GetString("Help_Code_RemoveCodeTagsSurroundingShortcodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove whitespaces surrounding shortcode content.
        /// </summary>
        internal static string Help_Code_RemoveWhitespacesSurroundingShortcodeContent {
            get {
                return ResourceManager.GetString("Help_Code_RemoveWhitespacesSurroundingShortcodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mixed language icon.
        /// </summary>
        internal static string Help_Code_ShowMixedLanguageIcon {
            get {
                return ResourceManager.GetString("Help_Code_ShowMixedLanguageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plain code by default.
        /// </summary>
        internal static string Help_Code_ShowPlainCodeByDefault {
            get {
                return ResourceManager.GetString("Help_Code_ShowPlainCodeByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab size in spaces.
        /// </summary>
        internal static string Help_Code_TabSizeInSpaces {
            get {
                return ResourceManager.GetString("Help_Code_TabSizeInSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Help_Content_Content {
            get {
                return ResourceManager.GetString("Help_Content_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont highlight.
        /// </summary>
        internal static string Help_Content_DontHighlight {
            get {
                return ResourceManager.GetString("Help_Content_DontHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        internal static string Help_Content_Inline {
            get {
                return ResourceManager.GetString("Help_Content_Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Help_Content_Language {
            get {
                return ResourceManager.GetString("Help_Content_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line range.
        /// </summary>
        internal static string Help_Content_LineRange {
            get {
                return ResourceManager.GetString("Help_Content_LineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked lines.
        /// </summary>
        internal static string Help_Content_MarkedLines {
            get {
                return ResourceManager.GetString("Help_Content_MarkedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Help_Content_Title {
            get {
                return ResourceManager.GetString("Help_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Help_Content_Url {
            get {
                return ResourceManager.GetString("Help_Content_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string Help_CustomOptions_Fonts {
            get {
                return ResourceManager.GetString("Help_CustomOptions_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Help_CustomOptions_Languages {
            get {
                return ResourceManager.GetString("Help_CustomOptions_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Help_CustomOptions_Themes {
            get {
                return ResourceManager.GetString("Help_CustomOptions_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string Help_Font_FontSize {
            get {
                return ResourceManager.GetString("Help_Font_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Help_Font_Name {
            get {
                return ResourceManager.GetString("Help_Font_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display numbers by default.
        /// </summary>
        internal static string Help_Lines_DisplayNumbersByDefault {
            get {
                return ResourceManager.GetString("Help_Lines_DisplayNumbersByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line marking.
        /// </summary>
        internal static string Help_Lines_EnableLineMarking {
            get {
                return ResourceManager.GetString("Help_Lines_EnableLineMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line number toggling.
        /// </summary>
        internal static string Help_Lines_EnableLineNumberToggling {
            get {
                return ResourceManager.GetString("Help_Lines_EnableLineNumberToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line ranges.
        /// </summary>
        internal static string Help_Lines_EnableLineRanges {
            get {
                return ResourceManager.GetString("Help_Lines_EnableLineRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line wrap toggling.
        /// </summary>
        internal static string Help_Lines_EnableLineWrapToggling {
            get {
                return ResourceManager.GetString("Help_Lines_EnableLineWrapToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting line number.
        /// </summary>
        internal static string Help_Lines_StartingLineNumber {
            get {
                return ResourceManager.GetString("Help_Lines_StartingLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Striped lines.
        /// </summary>
        internal static string Help_Lines_StripedLines {
            get {
                return ResourceManager.GetString("Help_Lines_StripedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap lines by default.
        /// </summary>
        internal static string Help_Lines_WrapLinesByDefault {
            get {
                return ResourceManager.GetString("Help_Lines_WrapLinesByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow floating elements to surround crayon.
        /// </summary>
        internal static string Help_Metrics_AllowFloatingElementsToSurroundCrayon {
            get {
                return ResourceManager.GetString("Help_Metrics_AllowFloatingElementsToSurroundCrayon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin.
        /// </summary>
        internal static string Help_Metrics_BottomMargin {
            get {
                return ResourceManager.GetString("Help_Metrics_BottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Help_Metrics_Height {
            get {
                return ResourceManager.GetString("Help_Metrics_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal alignment.
        /// </summary>
        internal static string Help_Metrics_HorizontalAlignment {
            get {
                return ResourceManager.GetString("Help_Metrics_HorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline margin.
        /// </summary>
        internal static string Help_Metrics_InlineMargin {
            get {
                return ResourceManager.GetString("Help_Metrics_InlineMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin.
        /// </summary>
        internal static string Help_Metrics_LeftMargin {
            get {
                return ResourceManager.GetString("Help_Metrics_LeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin.
        /// </summary>
        internal static string Help_Metrics_RightMargin {
            get {
                return ResourceManager.GetString("Help_Metrics_RightMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin.
        /// </summary>
        internal static string Help_Metrics_TopMargin {
            get {
                return ResourceManager.GetString("Help_Metrics_TopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Help_Metrics_Width {
            get {
                return ResourceManager.GetString("Help_Metrics_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to override this option from the global plugin settings.
        /// </summary>
        internal static string Help_Override {
            get {
                return ResourceManager.GetString("Help_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Help_Theme_Name {
            get {
                return ResourceManager.GetString("Help_Theme_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay hide on mouse out.
        /// </summary>
        internal static string Help_Toolbar_DelayHideOnMouseOut {
            get {
                return ResourceManager.GetString("Help_Toolbar_DelayHideOnMouseOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Help_Toolbar_Display {
            get {
                return ResourceManager.GetString("Help_Toolbar_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language display.
        /// </summary>
        internal static string Help_Toolbar_LanguageDisplay {
            get {
                return ResourceManager.GetString("Help_Toolbar_LanguageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay on code.
        /// </summary>
        internal static string Help_Toolbar_OverlayOnCode {
            get {
                return ResourceManager.GetString("Help_Toolbar_OverlayOnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title.
        /// </summary>
        internal static string Help_Toolbar_ShowTitle {
            get {
                return ResourceManager.GetString("Help_Toolbar_ShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle on single click when overlayed.
        /// </summary>
        internal static string Help_Toolbar_ToggleOnSingleClickWhenOverlayed {
            get {
                return ResourceManager.GetString("Help_Toolbar_ToggleOnSingleClickWhenOverlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to use the default setting for this option.
        /// </summary>
        internal static string Help_UseDefault {
            get {
                return ResourceManager.GetString("Help_UseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow floating elements to surround crayon.
        /// </summary>
        internal static string Label_AllowFloatingElementsToSurroundCrayon {
            get {
                return ResourceManager.GetString("Label_AllowFloatingElementsToSurroundCrayon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow mixed language highlighting with delimiters and tags.
        /// </summary>
        internal static string Label_AllowMixedLanguageHighlightingWithDelimitersAndTags {
            get {
                return ResourceManager.GetString("Label_AllowMixedLanguageHighlightingWithDelimitersAndTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always display scrollbars.
        /// </summary>
        internal static string Label_AlwaysDisplayScrollbars {
            get {
                return ResourceManager.GetString("Label_AlwaysDisplayScrollbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank lines after code.
        /// </summary>
        internal static string Label_BlankLinesAfterCode {
            get {
                return ResourceManager.GetString("Label_BlankLinesAfterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank lines before code.
        /// </summary>
        internal static string Label_BlankLinesBeforeCode {
            get {
                return ResourceManager.GetString("Label_BlankLinesBeforeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin.
        /// </summary>
        internal static string Label_BottomMargin {
            get {
                return ResourceManager.GetString("Label_BottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates during startup.
        /// </summary>
        internal static string Label_CheckForUpdates {
            get {
                return ResourceManager.GetString("Label_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check now....
        /// </summary>
        internal static string Label_CheckNow {
            get {
                return ResourceManager.GetString("Label_CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Label_Code {
            get {
                return ResourceManager.GetString("Label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Label_Content {
            get {
                return ResourceManager.GetString("Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode html entities in attributes.
        /// </summary>
        internal static string Label_DecodeHtmlEntitiesInAttributes {
            get {
                return ResourceManager.GetString("Label_DecodeHtmlEntitiesInAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay hide on mouse out.
        /// </summary>
        internal static string Label_DelayHideOnMouseOut {
            get {
                return ResourceManager.GetString("Label_DelayHideOnMouseOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Label_Display {
            get {
                return ResourceManager.GetString("Label_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display numbers by default.
        /// </summary>
        internal static string Label_DisplayNumbersByDefault {
            get {
                return ResourceManager.GetString("Label_DisplayNumbersByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t highlight.
        /// </summary>
        internal static string Label_DontHighlight {
            get {
                return ResourceManager.GetString("Label_DontHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable code expanding toggling.
        /// </summary>
        internal static string Label_EnableCodeExpandingToggling {
            get {
                return ResourceManager.GetString("Label_EnableCodeExpandingToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable copy paste.
        /// </summary>
        internal static string Label_EnableCopyPaste {
            get {
                return ResourceManager.GetString("Label_EnableCopyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line marking.
        /// </summary>
        internal static string Label_EnableLineMarking {
            get {
                return ResourceManager.GetString("Label_EnableLineMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line number toggling.
        /// </summary>
        internal static string Label_EnableLineNumberToggling {
            get {
                return ResourceManager.GetString("Label_EnableLineNumberToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line ranges.
        /// </summary>
        internal static string Label_EnableLineRanges {
            get {
                return ResourceManager.GetString("Label_EnableLineRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable line wrap toggling.
        /// </summary>
        internal static string Label_EnableLineWrapToggling {
            get {
                return ResourceManager.GetString("Label_EnableLineWrapToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable open in new window.
        /// </summary>
        internal static string Label_EnableOpenInNewWindow {
            get {
                return ResourceManager.GetString("Label_EnableOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable plain code toggling.
        /// </summary>
        internal static string Label_EnablePlainCodeToggling {
            get {
                return ResourceManager.GetString("Label_EnablePlainCodeToggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable plain code view.
        /// </summary>
        internal static string Label_EnablePlainCodeView {
            get {
                return ResourceManager.GetString("Label_EnablePlainCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand code beyond page border on mouse hover.
        /// </summary>
        internal static string Label_ExpandCodeBeyondPageBorderOnMouseHover {
            get {
                return ResourceManager.GetString("Label_ExpandCodeBeyondPageBorderOnMouseHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string Label_Fonts {
            get {
                return ResourceManager.GetString("Label_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string Label_FontSize {
            get {
                return ResourceManager.GetString("Label_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Label_Height {
            get {
                return ResourceManager.GetString("Label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal alignment.
        /// </summary>
        internal static string Label_HorizontalAlignment {
            get {
                return ResourceManager.GetString("Label_HorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include pre-release versions.
        /// </summary>
        internal static string Label_IncludePreReleaseVersions {
            get {
                return ResourceManager.GetString("Label_IncludePreReleaseVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Label_Information {
            get {
                return ResourceManager.GetString("Label_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        internal static string Label_Inline {
            get {
                return ResourceManager.GetString("Label_Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline margin.
        /// </summary>
        internal static string Label_InlineMargin {
            get {
                return ResourceManager.GetString("Label_InlineMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language display.
        /// </summary>
        internal static string Label_LanguageDisplay {
            get {
                return ResourceManager.GetString("Label_LanguageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Label_Languages {
            get {
                return ResourceManager.GetString("Label_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked at.
        /// </summary>
        internal static string Label_LastCheckedAt {
            get {
                return ResourceManager.GetString("Label_LastCheckedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin.
        /// </summary>
        internal static string Label_LeftMargin {
            get {
                return ResourceManager.GetString("Label_LeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line range.
        /// </summary>
        internal static string Label_LineRange {
            get {
                return ResourceManager.GetString("Label_LineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked lines.
        /// </summary>
        internal static string Label_MarkedLines {
            get {
                return ResourceManager.GetString("Label_MarkedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize code.
        /// </summary>
        internal static string Label_MinimizeCode {
            get {
                return ResourceManager.GetString("Label_MinimizeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay on code.
        /// </summary>
        internal static string Label_OverlayOnCode {
            get {
                return ResourceManager.GetString("Label_OverlayOnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        internal static string Label_Override {
            get {
                return ResourceManager.GetString("Label_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain code view display trigger.
        /// </summary>
        internal static string Label_PlainCodeViewDisplayTrigger {
            get {
                return ResourceManager.GetString("Label_PlainCodeViewDisplayTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in.
        /// </summary>
        internal static string Label_PlugIn {
            get {
                return ResourceManager.GetString("Label_PlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove code tags surrounding shortcode content.
        /// </summary>
        internal static string Label_RemoveCodeTagsSurroundingShortcodeContent {
            get {
                return ResourceManager.GetString("Label_RemoveCodeTagsSurroundingShortcodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove whitespaces surrounding shortcode content.
        /// </summary>
        internal static string Label_RemoveWhitespacesSurroundingShortcodeContent {
            get {
                return ResourceManager.GetString("Label_RemoveWhitespacesSurroundingShortcodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Label_Reset {
            get {
                return ResourceManager.GetString("Label_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin.
        /// </summary>
        internal static string Label_RightMargin {
            get {
                return ResourceManager.GetString("Label_RightMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string Label_SettingsPopup {
            get {
                return ResourceManager.GetString("Label_SettingsPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mixed language icon.
        /// </summary>
        internal static string Label_ShowMixedLanguageIcon {
            get {
                return ResourceManager.GetString("Label_ShowMixedLanguageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plain code by default.
        /// </summary>
        internal static string Label_ShowPlainCodeByDefault {
            get {
                return ResourceManager.GetString("Label_ShowPlainCodeByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title.
        /// </summary>
        internal static string Label_ShowTitle {
            get {
                return ResourceManager.GetString("Label_ShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting line number.
        /// </summary>
        internal static string Label_StartingLineNumber {
            get {
                return ResourceManager.GetString("Label_StartingLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Striped lines.
        /// </summary>
        internal static string Label_StripedLines {
            get {
                return ResourceManager.GetString("Label_StripedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab size in spaces.
        /// </summary>
        internal static string Label_TabSizeInSpaces {
            get {
                return ResourceManager.GetString("Label_TabSizeInSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Label_Themes {
            get {
                return ResourceManager.GetString("Label_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle on single click when overlayed.
        /// </summary>
        internal static string Label_ToggleOnSingleClickWhenOverlayed {
            get {
                return ResourceManager.GetString("Label_ToggleOnSingleClickWhenOverlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin.
        /// </summary>
        internal static string Label_TopMargin {
            get {
                return ResourceManager.GetString("Label_TopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Label_Update {
            get {
                return ResourceManager.GetString("Label_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update management.
        /// </summary>
        internal static string Label_UpdateManagement {
            get {
                return ResourceManager.GetString("Label_UpdateManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Label_Url {
            get {
                return ResourceManager.GetString("Label_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default.
        /// </summary>
        internal static string Label_UseDefault {
            get {
                return ResourceManager.GetString("Label_UseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Label_Warning {
            get {
                return ResourceManager.GetString("Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Label_Width {
            get {
                return ResourceManager.GetString("Label_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap lines by default.
        /// </summary>
        internal static string Label_WrapLinesByDefault {
            get {
                return ResourceManager.GetString("Label_WrapLinesByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; downloaded.
        /// </summary>
        internal static string Text_DownloadProgressCompletedMessageFormat_Version {
            get {
                return ResourceManager.GetString("Text_DownloadProgressCompletedMessageFormat_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading version {0}....
        /// </summary>
        internal static string Text_DownloadProgressMessageFormat_Version {
            get {
                return ResourceManager.GetString("Text_DownloadProgressMessageFormat_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel this download operation?.
        /// </summary>
        internal static string Text_DownloadUpdateCancelConfirmation {
            get {
                return ResourceManager.GetString("Text_DownloadUpdateCancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed version &apos;{0}&apos; is up to date.
        /// </summary>
        internal static string Text_InstalledVersionUpToDate_Version {
            get {
                return ResourceManager.GetString("Text_InstalledVersionUpToDate_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version &apos;{0}&apos; is available on the server. Would you like to download and installl this version?.
        /// </summary>
        internal static string Text_LatestVersionAvailableDownloadPrompt_Version {
            get {
                return ResourceManager.GetString("Text_LatestVersionAvailableDownloadPrompt_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {0} bytes out of {1} to be received....
        /// </summary>
        internal static string Text_ProgressMessage_Received_ToReceive {
            get {
                return ResourceManager.GetString("Text_ProgressMessage_Received_ToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        internal static string Title_DownloadUpdateForm {
            get {
                return ResourceManager.GetString("Title_DownloadUpdateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crayon Code Snippet Plug-in Options.
        /// </summary>
        internal static string Title_OptionsForm {
            get {
                return ResourceManager.GetString("Title_OptionsForm", resourceCulture);
            }
        }
    }
}
